const PDFDocument = require('pdfkit')
const path = require('path')
const fs = require('fs')

module.exports = function generateCommitteePdf(res, data) {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 50,
    bufferPages: true,
  })

  /* ================= HTTP HEADERS ================= */
  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=committee-report-${Date.now()}.pdf`
  )

  doc.pipe(res)

  /* ================= COLORS ================= */
  const colors = {
    primary: '#0f172a',
    accent: '#3b82f6',
    text: '#1e293b',
    lightText: '#475569',
    border: '#cbd5e1',
    darkBg: '#f8fafc',
    white: '#ffffff',
  }

  /* ================= HELPERS ================= */
  const drawLine = (y, color = colors.border, width = 515, x = 50) => {
    doc.moveTo(x, y).lineTo(x + width, y).strokeColor(color).lineWidth(0.5).stroke()
  }

  const drawBoldLine = (y, color = colors.accent, width = 515, x = 50) => {
    doc.moveTo(x, y).lineTo(x + width, y).strokeColor(color).lineWidth(2).stroke()
  }

  const addFooter = () => {
    const range = doc.bufferedPageRange()
    const now = new Date()
    const formattedDate = now.toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    })
    const formattedTime = now.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    })

    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i)

      // Footer separator line
      drawLine(745, colors.border, 515, 50)

      // Left side - Report info
      doc
        .fontSize(7)
        .fillColor(colors.lightText)
        .font('Helvetica')
        .text(
          `Generated by CRYSTALREPORT VICK01 ERP | Generation Timestamp: ${formattedDate} ${formattedTime}`,
          50,
          755,
          { align: 'left', width: 400 }
        )

      // Right side - Page number
      doc
        .fontSize(7)
        .fillColor(colors.lightText)
        .font('Helvetica')
        .text(
          `Page ${i + 1} of ${range.count}`,
          450,
          755,
          { align: 'right', width: 115 }
        )

      // Bottom confidentiality notice
      doc
        .fontSize(6)
        .fillColor('#94a3b8')
        .font('Helvetica')
        .text(
          'This is an official document. Unauthorized distribution is prohibited.',
          50,
          770,
          { align: 'center', width: 515 }
        )
    }
  }

  const drawTableHeader = (y) => {
    const headerHeight = 22
    const headerColor = colors.primary
    const textColor = colors.white

    // Background
    doc.rect(50, y, 515, headerHeight).fill(headerColor)

    // Headers with proper spacing
    doc.fontSize(9).fillColor(textColor).font('Helvetica-Bold')

    doc.text('Council ID', 60, y + 6, { width: 80 })
    doc.text('Member Name', 150, y + 6, { width: 130 })
    doc.text('Position', 290, y + 6, { width: 100 })
    doc.text('Attendance Days', 400, y + 6, { width: 80, align: 'center' })

    return y + headerHeight
  }

  const drawTableRow = (y, data, isTotal = false) => {
    const rowHeight = 18
    const bgColor = isTotal ? colors.darkBg : colors.white
    const textColor = isTotal ? colors.primary : colors.text
    const fontType = isTotal ? 'Helvetica-Bold' : 'Helvetica'
    const fontSize = isTotal ? 9.5 : 8.5

    // Row background
    doc.rect(50, y, 515, rowHeight).fill(bgColor)
    doc.strokeColor(colors.border).lineWidth(0.5).rect(50, y, 515, rowHeight).stroke()

    // Text
    doc.fontSize(fontSize).fillColor(textColor).font(fontType)

    doc.text(data.councilId, 60, y + 4, { width: 80 })
    doc.text(data.name, 150, y + 4, { width: 130 })
    doc.text(data.position, 290, y + 4, { width: 100 })
    doc.text(data.attendance, 400, y + 4, { width: 80, align: 'center' })

    return y + rowHeight
  }

  /* ================= LETTERHEAD WITH IMAGE ================= */
  // Letterhead image removed - report only mode
  doc.moveDown(0.5)

  /* ================= REPORT TITLE ================= */
  doc
    .fontSize(14)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('COMMITTEE INSIGHTS REPORT', { align: 'center' })

  doc.moveDown(0.2)

  doc
    .fontSize(9)
    .fillColor(colors.accent)
    .font('Helvetica')
    .text('Committee Performance and Member Record System', { align: 'center' })

  doc.moveDown(0.8)

  /* ================= METADATA SECTION ================= */
  const now = new Date()
  const formattedDate = now.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const formattedTime = now.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true,
  })

  doc.fontSize(8.5).fillColor(colors.lightText).font('Helvetica')
  doc.text(`Generation Date: ${formattedDate}`, { indent: 50 })
  doc.text(`Generation Time: ${formattedTime}`, { indent: 50 })

  doc.moveDown(0.5)
  drawBoldLine(doc.y, colors.accent, 515, 50)
  doc.moveDown(0.8)

  /* ================= COMMITTEE SUMMARY ================= */
  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('Committee Summary', { indent: 50 })

  doc.moveDown(0.4)

  // Summary box
  const summaryY = doc.y
  const summaryHeight = 100

  doc
    .strokeColor(colors.accent)
    .lineWidth(1)
    .rect(50, summaryY, 515, summaryHeight)
    .stroke()

  doc.rect(50, summaryY, 515, summaryHeight).fill(colors.darkBg)

  doc.fontSize(9.5).fillColor(colors.primary).font('Helvetica-Bold')

  let summaryItemY = summaryY + 15

  doc.text(`Committee Name: ${data.summary.committee}`, 65, summaryItemY)
  summaryItemY += 18

  doc.text(`Total Members: ${data.summary.totalMembers}`, 65, summaryItemY)
  summaryItemY += 18

  if (data.summary.attendanceRate !== undefined) {
    doc.text(`Attendance Rate: ${data.summary.attendanceRate}%`, 65, summaryItemY)
    summaryItemY += 18
  }

  if (data.summary.pendingLeaves !== undefined) {
    doc.text(`Pending Leaves: ${data.summary.pendingLeaves}`, 65, summaryItemY)
    summaryItemY += 18
  }

  if (data.summary.submittedReports !== undefined) {
    doc.text(`Submitted Reports: ${data.summary.submittedReports}`, 65, summaryItemY)
  }

  doc.moveDown(6.5)

  /* ================= ATTENDANCE CHART ================= */
  if (data.chartImage) {
    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .fillColor(colors.primary)
      .text('Attendance Trend Analysis', { indent: 50 })

    doc.moveDown(0.5)

    try {
      const base64 = data.chartImage.replace(
        /^data:image\/(png|jpeg|jpg);base64,/,
        ''
      )
      const imgBuffer = Buffer.from(base64, 'base64')

      doc.image(imgBuffer, 50, doc.y, {
        fit: [515, 250],
        align: 'center',
      })

      doc.moveDown(0.5)
    } catch (err) {
      console.error('Chart image error:', err)
      doc.fontSize(9).fillColor(colors.lightText).text('Chart image unavailable', { indent: 50 })
      doc.moveDown(0.5)
    }

    doc.moveDown(0.5)
    drawBoldLine(doc.y, colors.accent, 515, 50)
    doc.moveDown(0.8)
  }

  /* ================= MEMBERS TABLE ================= */
  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('Committee Members', { indent: 50 })

  doc.moveDown(0.4)

  let tableY = drawTableHeader(doc.y)
  doc.moveDown(0)

  let totalAttendanceDays = 0

  // Table Rows
  if (data.members && Array.isArray(data.members)) {
    for (const member of data.members) {
      // Page break check
      if (tableY > 720) {
        doc.addPage()
        tableY = 50
        tableY = drawTableHeader(tableY)
      }

      const attendanceDays = member.attendance_days || 0
      totalAttendanceDays += attendanceDays

      tableY = drawTableRow(tableY, {
        councilId: member.council_id || '-',
        name: member.name || '-',
        position: member.position || '-',
        attendance: attendanceDays > 0 ? `${attendanceDays} days` : '-',
      })
    }

    // Total Row
    if (data.members.length > 0) {
      tableY = drawTableRow(
        tableY,
        {
          councilId: '-',
          name: 'Committee Total',
          position: '-',
          attendance: `${totalAttendanceDays} days`,
        },
        true
      )
    }
  } else {
    doc.fontSize(9).fillColor(colors.lightText).text('No member data available', { indent: 50 })
  }

  /* ================= FOOTER ================= */
  addFooter()

  doc.end()
}