const PDFDocument = require('pdfkit')
const path = require('path')
const fs = require('fs')

module.exports = function generateAttendancePdf(res, reportData, meta) {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 50,
    bufferPages: true,
  })

  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=attendance-report-${Date.now()}.pdf`
  )

  doc.pipe(res)

  // ==================== COLORS ====================
  const colors = {
    primary: '#0f172a',
    accent: '#3b82f6',
    light: '#f0f9ff',
    text: '#1e293b',
    lightText: '#475569',
    border: '#cbd5e1',
    header: '#020617',
    darkBg: '#f8fafc',
  }

  // ==================== HELPERS ====================
  const drawLine = (y, color = colors.border, width = 515, x = 50) => {
    doc.moveTo(x, y).lineTo(x + width, y).strokeColor(color).lineWidth(0.5).stroke()
  }

  const drawBoldLine = (y, color = colors.accent, width = 515, x = 50) => {
    doc.moveTo(x, y).lineTo(x + width, y).strokeColor(color).lineWidth(2).stroke()
  }

  const addFooter = () => {
    const range = doc.bufferedPageRange()
    const now = new Date()
    const formattedDate = now.toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    })
    const formattedTime = now.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    })

    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i)

      // Footer separator line
      drawLine(745, colors.border, 515, 50)

      // Left side - Report info
      doc
        .fontSize(7)
        .fillColor(colors.lightText)
        .font('Helvetica')
        .text(
          `Generated by CRYSTALREPORT VICK01 ERP | Generation Timestamp: ${formattedDate} ${formattedTime}`,
          50,
          755,
          { align: 'left', width: 400 }
        )

      // Right side - Page number
      doc
        .fontSize(7)
        .fillColor(colors.lightText)
        .font('Helvetica')
        .text(
          `Page ${i + 1} of ${range.count}`,
          450,
          755,
          { align: 'right', width: 115 }
        )

      // Bottom confidentiality notice
      doc
        .fontSize(6)
        .fillColor('#94a3b8')
        .font('Helvetica')
        .text(
          'This is an official document. Unauthorized distribution is prohibited.',
          50,
          770,
          { align: 'center', width: 515 }
        )
    }
  }

  const drawTableHeader = (y) => {
    const headerHeight = 22
    const headerColor = colors.primary
    const textColor = colors.white

    // Background
    doc.rect(50, y, 515, headerHeight).fill(headerColor)

    // Headers with proper spacing
    doc.fontSize(9).fillColor(textColor).font('Helvetica-Bold')

    doc.text('Member Name', 60, y + 6, { width: 140 })
    doc.text('Attendance Days', 210, y + 6, { width: 80, align: 'center' })
    doc.text('Total Hours', 300, y + 6, { width: 70, align: 'center' })
    doc.text('Weekly Avg', 380, y + 6, { width: 70, align: 'center' })
    doc.text('Daily Avg', 460, y + 6, { width: 60, align: 'right' })

    return y + headerHeight
  }

  const drawTableRow = (y, data, isTotal = false) => {
    const rowHeight = 18
    const bgColor = isTotal ? colors.darkBg : '#ffffff'
    const textColor = isTotal ? colors.primary : colors.text
    const fontType = isTotal ? 'Helvetica-Bold' : 'Helvetica'
    const fontSize = isTotal ? 9.5 : 8.5

    // Row background
    doc.rect(50, y, 515, rowHeight).fill(bgColor)
    doc.strokeColor(colors.border).lineWidth(0.5).rect(50, y, 515, rowHeight).stroke()

    // Text
    doc.fontSize(fontSize).fillColor(textColor).font(fontType)

    doc.text(data.name, 60, y + 4, { width: 140 })
    doc.text(data.attendance, 210, y + 4, { width: 80, align: 'center' })
    doc.text(data.hours, 300, y + 4, { width: 70, align: 'center' })
    doc.text(data.weekly, 380, y + 4, { width: 70, align: 'center' })
    doc.text(data.daily, 460, y + 4, { width: 60, align: 'right' })

    return y + rowHeight
  }

  // ==================== LETTERHEAD WITH IMAGE ====================
  // Letterhead image removed - report only mode
  doc.moveDown(0.5)

  // ==================== REPORT TITLE ====================
  doc
    .fontSize(14)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('ATTENDANCE REPORT', { align: 'center' })

  doc.moveDown(0.2)

  doc
    .fontSize(9)
    .fillColor(colors.accent)
    .font('Helvetica')
    .text('Personnel Attendance Record System', { align: 'center' })

  doc.moveDown(0.8)

  // ==================== METADATA ====================
  const now = new Date()
  const formattedDate = now.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const formattedTime = now.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true,
  })

  doc.fontSize(8.5).fillColor(colors.lightText).font('Helvetica')
  doc.text(`Report Period Start: ${meta.startDate}`, { indent: 50 })
  doc.text(`Report Period End: ${meta.endDate}`, { indent: 50 })
  doc.text(
    `Committee Filter: ${meta.committee === 'all' ? 'All Committees' : meta.committee}`,
    { indent: 50 }
  )
  doc.text(`Generation Date: ${formattedDate}`, { indent: 50 })
  doc.text(`Generation Time: ${formattedTime}`, { indent: 50 })

  doc.moveDown(0.5)
  drawBoldLine(doc.y, colors.accent, 515, 50)
  doc.moveDown(0.8)

  let pageY = doc.y
  let overall = { attendance: 0, hours: 0 }

  // ==================== COMMITTEES ====================
  for (const committee of reportData) {
    // Page break check before committee title
    if (pageY > 700) {
      doc.addPage()
      pageY = 50
    }

    // Committee Title
    doc
      .fontSize(11)
      .fillColor(colors.primary)
      .font('Helvetica-Bold')
      .text(`${committee.committee}`, { indent: 50 })

    doc.moveDown(0.2)
    pageY = doc.y

    // Committee Head
    doc
      .fontSize(8)
      .fillColor(colors.lightText)
      .font('Helvetica')
      .text(`Committee Head: ${committee.head || 'Not Assigned'}`, { indent: 50 })

    doc.moveDown(0.3)
    pageY = doc.y

    // Table Header
    pageY = drawTableHeader(pageY)
    doc.moveDown(0)

    let committeeTotal = { attendance: 0, hours: 0 }

    // Table Rows
    for (const member of committee.members) {
      // Page break check
      if (pageY > 720) {
        doc.addPage()
        pageY = 50
        pageY = drawTableHeader(pageY)
      }

      const attendance = `${member.attendance}`
      const hours = `${Number(member.totalHours).toFixed(2)}`
      const weekly = `${Number(member.weeklyAvg).toFixed(2)}`
      const daily = `${Number(member.dailyAvg).toFixed(2)}`

      pageY = drawTableRow(pageY, {
        name: member.name,
        attendance,
        hours,
        weekly,
        daily,
      })

      committeeTotal.attendance += member.attendance
      committeeTotal.hours += Number(member.totalHours)
      overall.attendance += member.attendance
      overall.hours += Number(member.totalHours)
    }

    // Committee Total Row
    pageY = drawTableRow(
      pageY,
      {
        name: `${committee.committee} - Total`,
        attendance: `${committeeTotal.attendance}`,
        hours: `${committeeTotal.hours.toFixed(2)}`,
        weekly: '-',
        daily: '-',
      },
      true
    )

    doc.moveDown(0.8)
    pageY = doc.y
  }

  // ==================== SUMMARY SECTION ====================
  if (pageY > 680) {
    doc.addPage()
    pageY = 50
  }

  doc.moveDown(0.3)
  drawBoldLine(doc.y, colors.accent, 515, 50)
  doc.moveDown(0.6)

  // Summary Title
  doc
    .fontSize(11)
    .fillColor(colors.primary)
    .font('Helvetica-Bold')
    .text('SUMMARY OF ATTENDANCE', { indent: 50 })

  doc.moveDown(0.4)

  // Summary Box
  const summaryY = doc.y
  const summaryHeight = 70

  // Box border
  doc
    .strokeColor(colors.accent)
    .lineWidth(1)
    .rect(50, summaryY, 515, summaryHeight)
    .stroke()

  // Fill light background
  doc.rect(50, summaryY, 515, summaryHeight).fill(colors.light)

  // Summary content
  doc.fontSize(9.5).fillColor(colors.primary).font('Helvetica-Bold')

  doc.text(`Total Attendance Days: ${overall.attendance} days`, 65, summaryY + 12)
  doc.text(`Total Working Hours: ${overall.hours.toFixed(2)} hours`, 65, summaryY + 30)
  doc.text(
    `Average Daily Hours: ${(overall.hours / Math.max(overall.attendance, 1)).toFixed(2)} hours`,
    65,
    summaryY + 48
  )

  // ==================== FINAL FOOTER ====================
  addFooter()

  doc.end()
}