const PDFDocument = require('pdfkit')
const path = require('path')
const fs = require('fs')

module.exports = function generateLogsPdf(res, payload) {
  const { title, filters, logs } = payload

  const doc = new PDFDocument({
    size: 'A4',
    landscape: true,
    margin: 20,
    bufferPages: true,
    autoFirstPage: false,
  })

  // Add first page with landscape rotation
  doc.addPage({ size: 'A4', landscape: true })

  /* ================= HTTP HEADERS ================= */
  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=logs-report-${Date.now()}.pdf`
  )

  doc.pipe(res)

  /* ================= COLORS ================= */
  const colors = {
    primary: '#0f172a',
    accent: '#3b82f6',
    text: '#1e293b',
    lightText: '#475569',
    border: '#cbd5e1',
    darkBg: '#f8fafc',
    white: '#ffffff',
    info: '#3b82f6',
    warning: '#f59e0b',
    error: '#ef4444',
  }

  /* ================= HELPERS ================= */
  const drawLine = (y, color = colors.border, width = 840, x = 20) => {
    doc.moveTo(x, y).lineTo(x + width, y).strokeColor(color).lineWidth(0.5).stroke()
  }

  const drawBoldLine = (y, color = colors.accent, width = 840, x = 20) => {
    doc.moveTo(x, y).lineTo(x + width, y).strokeColor(color).lineWidth(2).stroke()
  }

  const getSeverityColor = (severity) => {
    switch (severity?.toUpperCase()) {
      case 'ERROR':
        return colors.error
      case 'WARNING':
        return colors.warning
      case 'INFO':
        return colors.info
      default:
        return colors.text
    }
  }

  const addFooter = () => {
    const range = doc.bufferedPageRange()
    const now = new Date()
    const formattedDate = now.toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    })
    const formattedTime = now.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    })

    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i)

      // Save and rotate footer
      doc.save()
      doc.translate(400, 300)
      doc.rotate(90)
      doc.translate(-300, -400)

      // Footer separator line
      drawLine(750, colors.border, 800, 40)

      // Left side - Report info
      doc
        .fontSize(7)
        .fillColor(colors.lightText)
        .font('Helvetica')
        .text(
          `Generated by CRYSTALREPORT VICK01 ERP | Generation Timestamp: ${formattedDate} ${formattedTime}`,
          40,
          760,
          { align: 'left', width: 500 }
        )

      // Right side - Page number
      doc
        .fontSize(7)
        .fillColor(colors.lightText)
        .font('Helvetica')
        .text(
          `Page ${i + 1} of ${range.count}`,
          750,
          760,
          { align: 'right', width: 90 }
        )

      // Restore rotation
      doc.restore()
    }
  }

  const drawTableHeader = (y) => {
    const headerHeight = 28
    const headerColor = colors.primary
    const textColor = colors.white

    // Background
    doc.rect(20, y, 840, headerHeight).fill(headerColor)

    // Headers with proper spacing for landscape
    doc.fontSize(9).fillColor(textColor).font('Helvetica-Bold')

    doc.text('User', 30, y + 8, { width: 70, align: 'left' })
    doc.text('Action', 105, y + 8, { width: 70, align: 'left' })
    doc.text('Severity', 180, y + 8, { width: 60, align: 'center' })
    doc.text('Committee', 245, y + 8, { width: 100, align: 'left' })
    doc.text('Description', 350, y + 8, { width: 380, align: 'left' })
    doc.text('Timestamp', 735, y + 8, { width: 85, align: 'center' })

    return y + headerHeight
  }

  const drawTableRow = (y, data, isAlternate = false) => {
    const rowHeight = 24
    const bgColor = isAlternate ? colors.darkBg : colors.white
    const textColor = colors.text
    const fontSize = 8

    // Row background
    doc.rect(20, y, 840, rowHeight).fill(bgColor)
    doc.strokeColor(colors.border).lineWidth(0.5).rect(20, y, 840, rowHeight).stroke()

    // Severity color indicator (left border)
    const severityColor = getSeverityColor(data.severity)
    doc
      .strokeColor(severityColor)
      .lineWidth(3)
      .moveTo(20, y)
      .lineTo(20, y + rowHeight)
      .stroke()

    // Text
    doc.fontSize(fontSize).font('Helvetica')

    doc.fillColor(colors.text).text(data.user, 30, y + 6, { width: 70 })
    doc.fillColor(colors.text).text(data.action, 105, y + 6, { width: 70 })

    // Severity badge
    const severityBgColor = severityColor + '20'
    doc
      .rect(180, y + 7, 60, 10)
      .fill(severityBgColor)
      .stroke()
    doc
      .fillColor(severityColor)
      .font('Helvetica-Bold')
      .fontSize(7)
      .text(data.severity || '-', 183, y + 7, { width: 54, align: 'center' })

    doc
      .font('Helvetica')
      .fontSize(fontSize)
      .fillColor(colors.text)
      .text(data.committee || '-', 245, y + 6, { width: 100 })

    // Full description with maximum width
    doc.fillColor(colors.lightText).fontSize(fontSize).text(data.description, 350, y + 6, { width: 380 })

    const timestamp = new Date(data.created_at).toLocaleString('en-US', {
      month: '2-digit',
      day: '2-digit',
      year: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true,
    })
    doc.fillColor(colors.lightText).text(timestamp, 735, y + 6, { width: 85, align: 'center' })

    return y + rowHeight
  }

  /* ================= SAVE STATE FOR ROTATION ================= */
  doc.save()
  
  // Move to center and rotate for landscape horizontal printing
  doc.translate(400, 300)
  doc.rotate(90)
  doc.translate(-300, -400)

  /* ================= REPORT TITLE ================= */
  doc.moveDown(0.3)

  doc
    .fontSize(18)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('SYSTEM LOGS REPORT', 20, 50, { align: 'left', width: 600 })

  doc
    .fontSize(10)
    .fillColor(colors.accent)
    .font('Helvetica')
    .text('Comprehensive System Activity and Event Log Record', 20, 72, { align: 'left', width: 600 })

  // Add confidentiality notice on header right side
  doc
    .fontSize(7)
    .fillColor('#94a3b8')
    .font('Helvetica')
    .text('This is an official document. Unauthorized distribution is prohibited.', 670, 50, { align: 'right', width: 170 })

  doc.moveDown(0.8)

  /* ================= METADATA SECTION ================= */
  const now = new Date()
  const formattedDate = now.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const formattedTime = now.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true,
  })

  doc.fontSize(9).fillColor(colors.lightText).font('Helvetica')
  doc.text(`Report Title: ${title}`, 20, 100)
  doc.text(`Generation Date: ${formattedDate}`, 20, 115)
  doc.text(`Generation Time: ${formattedTime}`, 20, 130)
  doc.text(`Total Log Entries: ${logs.length || 0}`, 20, 145)

  doc.moveDown(1)
  drawBoldLine(160, colors.accent, 840, 20)

  /* ================= FILTER SUMMARY ================= */
  doc
    .fontSize(11)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('Applied Filters', 20, 175)

  doc.moveDown(0.3)

  const activeFilters = Object.entries(filters)
    .filter(([key, value]) => value && value !== '')
    .map(([key, value]) => `${key}: ${value}`)

  if (activeFilters.length > 0) {
    doc
      .fontSize(9)
      .fillColor(colors.text)
      .font('Helvetica')
      .text(activeFilters.join(' | '), 20, 195)
  } else {
    doc
      .fontSize(9)
      .fillColor(colors.lightText)
      .font('Helvetica')
      .text('No filters applied - all logs displayed', 20, 195)
  }

  drawBoldLine(220, colors.accent, 840, 20)

  /* ================= LOGS TABLE ================= */
  doc
    .fontSize(11)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('System Activity Log', 20, 235)

  let tableY = drawTableHeader(260)

  // Table Rows
  if (logs && Array.isArray(logs) && logs.length > 0) {
    logs.forEach((log, index) => {
      // Page break check
      if (tableY > 700) {
        doc.restore()
        doc.addPage({ size: 'A4', landscape: true })
        doc.save()
        doc.translate(400, 300)
        doc.rotate(90)
        doc.translate(-300, -400)
        
        tableY = 50
        tableY = drawTableHeader(tableY)
      }

      tableY = drawTableRow(
        tableY,
        {
          user: log.user || 'SYSTEM',
          action: log.action || '-',
          severity: log.severity || 'INFO',
          committee: log.committee || '-',
          description: log.description || '-',
          created_at: log.created_at || new Date().toISOString(),
        },
        index % 2 !== 0
      )
    })
  } else {
    doc
      .fontSize(9)
      .fillColor(colors.lightText)
      .font('Helvetica')
      .text('No log entries found for the specified criteria', 40, tableY + 10)

    tableY += 30
  }

  /* ================= SUMMARY STATISTICS ================= */
  if (logs && Array.isArray(logs) && logs.length > 0) {
    tableY += 20
    drawBoldLine(tableY, colors.accent, 840, 20)
    tableY += 20

    doc
      .fontSize(11)
      .font('Helvetica-Bold')
      .fillColor(colors.primary)
      .text('Log Summary Statistics', 20, tableY)

    tableY += 25

    // Count by severity
    const severityCounts = {}
    logs.forEach(log => {
      const severity = log.severity || 'INFO'
      severityCounts[severity] = (severityCounts[severity] || 0) + 1
    })

    // Count by action
    const actionCounts = {}
    logs.forEach(log => {
      const action = log.action || 'Unknown'
      actionCounts[action] = (actionCounts[action] || 0) + 1
    })

    // Column positioning
    const leftX = 20
    const rightX = 330

    // Left column - Severity counts
    doc.fontSize(10).fillColor(colors.primary).font('Helvetica-Bold')
    doc.text('By Severity', leftX, tableY)

    let severityY = tableY + 20
    doc.fontSize(9).fillColor(colors.text).font('Helvetica')
    doc.text(`Total Entries: ${logs.length}`, leftX + 20, severityY)
    
    severityY += 15
    Object.entries(severityCounts).forEach(([severity, count]) => {
      doc
        .fontSize(9)
        .fillColor(getSeverityColor(severity))
        .font('Helvetica')
        .text(`${severity}: ${count}`, leftX + 20, severityY)
      severityY += 15
    })

    // Right column - Action counts
    doc.fontSize(10).fillColor(colors.primary).font('Helvetica-Bold')
    doc.text('By Action', rightX, tableY)

    let actionY = tableY + 20
    Object.entries(actionCounts).forEach(([action, count]) => {
      doc
        .fontSize(9)
        .fillColor(colors.text)
        .font('Helvetica')
        .text(`${action}: ${count}`, rightX + 20, actionY)
      actionY += 15
    })
  }

  /* ================= RESTORE AND FOOTER ================= */
  doc.restore()
  addFooter()

  doc.end()
}